Back/AspNet_Postgress/AspNet_Postgress/Models/Category.cs
namespace AspNet_Postgress.Models
{
    public class Category
    {
        public int id { get; set; }
        public string name { get; set; }
        
    }
}

Back/AspNet_Postgress/AspNet_Postgress/Models/ErrorViewModel.cs
namespace AspNet_Postgress.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Back/AspNet_Postgress/AspNet_Postgress/Models/Product.cs
namespace AspNet_Postgress.Models
{
    public class Product
    {
        public int id { get; set; }
        public string name { get; set;}
    }
}

Back/AspNet_Postgress/AspNet_Postgress/Models/ProductCategory.cs
namespace AspNet_Postgress.Models
{
    public class ProductCategory
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdCategory { get; set; }

    }
}

Back/AspNet_Postgress/AspNet_Postgress/Controllers/HomeController.cs
using AspNet_Postgress.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspNet_Postgress.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Back/AspNet_Postgress/AspNet_Postgress/Controllers/ProductCategoryController.cs
using AspNet_Postgress.Data;
using Microsoft.AspNetCore.Mvc;

namespace AspNet_Postgress.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly DataContext _context;

        public ProductCategoryController(DataContext context)
        {
            _context = context;
            bool isWork = _context.Database.CanConnect();
            bool isAdmin = _context.Database.CanConnect();
        }

        public IActionResult Index()
        {
            Console.WriteLine(_context.Database.CanConnect());

            var listProduct = _context.product;

            return View(listProduct);
        }
    }
}

Back/AspNet_Postgress/AspNet_Postgress/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Back/AspNet_Postgress/AspNet_Postgress/Views/ProductCategory/Index.cshtml
@model IEnumerable<Product>

<div>
    <table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Название
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="50%">
                    @item.name
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

</div>

Back/AspNet_Postgress/AspNet_Postgress/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet_Postgress</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNet_Postgress.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNet_Postgress</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductCategory" asp-action="Index">Product-Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspNet_Postgress - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>